[package]
name = "falconeri_common"
version = "1.0.0-beta.12"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { version = "1.0.45", features = ["backtrace"] }
async-trait = "0.1"
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.22"
cast = { version = "0.3.0", features = ["std"] }
chrono = { version = "0.4.4", features = ["serde"] }
diesel = { version = "2.3", features = ["chrono", "postgres", "serde_json", "uuid"] }
diesel-async = { version = "0.7", features = ["postgres", "deadpool", "migrations"] }
diesel_migrations = "2.3"
futures-util = "0.3"
handlebars = "6"
humantime-serde = "1.0.1"
lazy_static = "1.0.2"
rand = "0.9"
regex = "1.0.2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots"] }
semver = "1.0.4"
serde = "1.0.70"
serde_json = "1.0"
openssl-probe = "0.1.6"
tokio = { version = "1", features = ["process", "io-util"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.2", features = ["env-filter"] }
url = "2.2.2"
uuid = { version = "1.3.3", features = ["serde", "v4"] }
