[book]
authors = ["Eric Kidd"]
src = "src"
title = "falconeri: Distributed batch processing using Kubernetes"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.pdf]

[preprocessor.mermaid]
command = "mdbook-mermaid"
