[book]
authors = ["Eric Kidd"]
multilingual = false
src = "src"
title = "falconeri Distributed batch processing using Kubernetes"

[output.html]

[output.typst-pdf]
pdf = true
custom-template = "template.typ"
section-number = true
chapter-no-pagebreak = false
